
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: basl_backup
  pool: 5
  username: test
  password: "12345"
  socket: /tmp/mysql.sock

default: &default
  adapter: postgresql
  encoding: unicode
  database: basl_backup_dev
  pool: 5
  username: basl
  password: 1234

production:
  adapter: postgresql
  encoding: unicode
  database: basl_backup_prod
  pool: 5
  username: basl
  password: 1234

